
@baseUrl = http://localhost:8000/api
@username = admin
@password = admin

###
GET {{baseUrl}}/1
Authorization: Digest {{username}} {{password}}
Accept: application/json

###
POST {{baseUrl}}/2
Authorization: Digest {{username}} {{password}}
Accept: application/json

{"did":1}

###
POST {{baseUrl}}/3
Authorization: Digest {{username}} {{password}}
Accept: application/json

{}

###
POST {{baseUrl}}/4
Authorization: Digest {{username}} {{password}}
Accept: application/json

{
    "did":12677,
    "chart_names":[
        "session_stats",
        "tps_stats",
        "ti_stats",
        "to_stats",
        "bio_stats"
    ]
}

### 获取主机基本信息
GET {{baseUrl}}/host/baseinfo
Authorization: Digest {{username}} {{password}}
Authentication-Mode: digest
Accept: application/json


### 获取主机基本信息
GET {{baseUrl}}/host/osinfo
Authorization: Digest {{username}} {{password}}
Authentication-Mode: digest
Accept: application/json

### 获取主机存储信息
GET {{baseUrl}}/host/storage
Authorization: Digest {{username}} {{password}}
Authentication-Mode: digest
Accept: application/json

### 获取主机性能指标
GET {{baseUrl}}/host/pref
Authorization: Digest {{username}} {{password}}
Authentication-Mode: digest
Accept: application/json


### 获取greenplum的节点信息
GET {{baseUrl}}/gp/segments
Authorization: Digest {{username}} {{password}}
Authentication-Mode: digest
Accept: application/json

### 获取正在执行的查询
GET {{baseUrl}}/gp/activity_queries
Authorization: Digest {{username}} {{password}}
Authentication-Mode: digest
Accept: application/json

###